" gvimrc
" The author disclaims copyright to this source code. It is placed in
" the public domain. In case this is not legally possible I grant anyone
" the right to use it for any purpose, without any conditions, unless
" such conditions are required by law.

set guifont=Droid\ Sans\ Mono\ 11
set background=light
" remove menu bar
set guioptions-=m
" remove toolbar
set guioptions-=T
" use vim style popup dialogs
set guioptions+=c
