" vimrc
" The author disclaims copyright to this source code. It is placed in
" the public domain. In case this is not legally possible I grant anyone
" the right to use it for any purpose, without any conditions, unless
" such conditions are required by law.

" Workaround for compatibility with py3.7.
" https://github.com/vim/vim/issues/3117
" https://github.com/SirVer/ultisnips/issues/996
if has('python3')
  silent! python3 1
endif

" use vim defaults instead of vi ones
set nocompatible

" enable pathogen and load plugins from ~/.vim/bundle
call pathogen#helptags()
call pathogen#infect()

" turn syntax highlight on
syntax on
" use light colors
set background=dark
" directory for swap files
set directory=~/.vim/tmp
" directory for backup files
set backupdir=~/.vim/tmp
" always backup files, don't delete backups after a successful write
set backup
set writebackup
" fold blocks with the same indentation
set foldmethod=indent
" hide unused buffers instead of closing
set hidden
" enable file type detection
filetype on
" disable file type dependent auto indent
filetype indent off
" enable file type dependent general configuration
filetype plugin on
" keep indentation
set autoindent
" use whatever characters were used for indenting the previous line
set copyindent
" <Tab> counts for 8 spaces
set tabstop=8
" 4 spaces for one step of autoindent
set shiftwidth=4
" delete 4 spaces with one backspace
set softtabstop=4
" use spaces instead of tab characters
set expandtab
" don't move the cursor to beginning of the line after a buffer change
set nostartofline
" don't wrap lines
set nowrap
" ignore case of typed search text only if typed using only small letters
set ignorecase
set smartcase
" search as you type
set incsearch
" allow backspacing over everything in insert mode
set backspace=indent,eol,start
" heep 1000 lines of command history
set history=1000
" heep 1000 levels of undo
set undolevels=1000
" show coursor position all the time
set ruler
" show partialy written commands
set showcmd
" wrap text to 80 characters, don't auto break lines
set textwidth=80
autocmd FileType * setlocal formatoptions-=t
autocmd FileType * setlocal formatoptions-=c
" set file encoding
set encoding=utf-8
" zsh like completion for commands like :edit
set wildmode=list:longest
" highlight tabs and trailing spaces
set listchars=tab:>-,trail:-
set list
" search highlight
set hlsearch
" disable viminfo
set viminfo=
" make omnicompletion popup show most matching strings
set completeopt=longest,menuone

" Use terminal colors, 256 colors don't look good on either the default or black
" background.
let g:gruvbox_termcolors=16
colorscheme gruvbox

" prevent accidental exits, only `:quit` will exit vim
cabbrev q <c-r>=(getcmdtype()==':' && getcmdpos()==1 ? 'close' : 'q')<CR>
cabbrev wq <c-r>=(getcmdtype()==':' && getcmdpos()==1 ? 'write' : 'wq')<CR>
cabbrev wqa <c-r>=(getcmdtype()==':' && getcmdpos()==1 ? 'wall' : 'wqa')<CR>

" enable indentation for Ruby files
autocmd FileType ruby runtime indent/ruby.vim
autocmd FileType ruby setlocal shiftwidth=2 softtabstop=2
" enable indentation for Python files
autocmd FileType python runtime indent/python.vim
" set default indentation to 2 spaces for javascript files
autocmd FileType javascript setlocal shiftwidth=2 softtabstop=2
" set default indentation to 2 spaces for php files
autocmd FileType php setlocal shiftwidth=2 softtabstop=2
" auto break git commit message lines at 72 characters, also turn on spell
" checking by default
autocmd FileType gitcommit setlocal textwidth=72 formatoptions+=t spell spelllang=en_us
" turn on spell checking by default
autocmd FileType markdown setlocal spell spelllang=en_us
" .md files are markdown files, not modula2
autocmd BufNewFile,BufRead *.md set filetype=markdown
" treat .json files as javascript to get syntax highlighting
autocmd BufNewFile,BufRead *.json set filetype=javascript

" set keys for NERDTree
nnoremap <Leader>f <Esc>:NERDTreeToggle<CR>
" close NERDTree after opening a file
let NERDTreeQuitOnOpen = 1

" load snippets from a custom dir
let g:UltiSnipsSnippetDirectories=["ultisnips_snippets"]

" Gj will put the cursor on second line (last used buffer)
nnoremap <Leader>d <Esc>:Bufferlist<CR>Gj
" disable in buffet window key mappings
let g:buffetdisabledefaultmaps = 1

" Disable running Hack typechecker on file save
let hack#enable = 0
" Same for flow
let g:flow#enable = 0

" delete trailing spaces
nnoremap <F1> :%s/\s\+$//e<CR>
" set indent to two spaces
nnoremap <F2> :setlocal shiftwidth=2<CR>:setlocal softtabstop=2<CR>
" set indent to four spaces
nnoremap <F3> :setlocal shiftwidth=4<CR>:setlocal softtabstop=4<CR>
" enable spell checking
nnoremap <F4> :setlocal spell spelllang=en_us<CR>
" show undo history
nnoremap <F5> :GundoToggle<CR>
" trigger omnicomplete
inoremap <c-x>n <c-x><c-o>
